apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: core
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: angular-app

  template:
    metadata:
      labels:
        app: angular-app
      annotations:
        prometheus.io/scrape: "false"

    spec:
      containers:
        - name: angular-app
          image: serhiiharas/angular-app:v1.0.25
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app
  namespace: core
spec:
  selector:
    app: angular-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular-app
  namespace: core
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - angular.haras.space
      secretName: rancher-tls
  rules:
    - host: angular.haras.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angular-app
                port:
                  number: 80
