apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: serhiiharas/angular-app:v1.0.20
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app
  namespace: core
spec:
  selector:
    app: angular-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular-app
  namespace: core
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      try_files $uri $uri/ /index.html;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - angular.haras.space
      secretName: rancher-tls
  rules:
    - host: angular.haras.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angular-app
                port:
                  number: 80
